name = "bags-shark-tank-api"
main = "worker.js"
compatibility_date = "2024-01-01"

# Workers Sites configuration
[site]
bucket = ""

# Environment variables (добавь свой Helius API key через dashboard)
[vars]
HELIUS_KEY = "YOUR_KEY_HERE"